// Caravel User Project Wrapper for Tiny Tapeout
// This module connects our FSM and CPU to the Caravel infrastructure.

module user_project_wrapper (
    input wire wb_clk_i, // Wishbone clock
    input wire wb_rst_i, // Wishbone reset
    // Caravel Wishbone interface (to be auto-generated by Copilot)
);

// Wrapper implementation goes here

endmodule